### ISSUE TITLE
Rider 2020.1 EAP 4 NoSuchMethodError

### ISSUE THREAD

**Issue by SKProCH** [ForNeVeR/AvaloniaRider#120]
## Rider info:
```
JetBrains Rider 2021.1 EAP 4
Build #RD-211.6085.25, built on February 18, 2021
Rider EAP User
Expiration date: March 20, 2021
Runtime version: 11.0.10+9-b1341.2 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, ide.windowSystem.autoShowProcessPopup=true, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: Statistic (4.1.7), com.intellij.ideolog (203.0.26.0), com.intellij.javafx (1.0.3), avalonia-rider (1.0.0.586682461), com.samdark.intellij-visual-studio-code-dark-plus (2.2), lermitage.intellij.extra.icons (1.46.1.201), net.vektah.codeglance (1.5.4), Gitflow (0.7.5), com.microsoft.vso.idea (1.161.1), zielu.gittoolbox (203.4.8), Jetbrains TeamCity Plugin (2020.2.85899), some.awesome (1.14), izhangzhihao.rainbow.brackets (6.15), cn.yiiguxing.plugin.translate (3.0.1), tanvd.grazi (211.6085.3)
```
### Exception in plugin AvaloniaRider
```
java.lang.NoSuchMethodError: 'java.lang.Object com.jetbrains.rider.util.CoroutineUtilKt.startOnUi$default(com.jetbrains.rd.util.lifetime.Lifetime, com.intellij.openapi.application.ModalityState, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation, int, java.lang.Object)'
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController.executePreviewerAsync(AvaloniaPreviewerSessionController.kt:229)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$start$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:292)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
### Exception in Rider Core:
```
com.jetbrains.rdclient.util.BackendException: Component ReSharperPlugin.AvaloniaRider.RiderProjectOutputHost [Singleton, Corrupted] construction has failed. Адресат вызова создал исключение. Метод не найден: "Void JetBrains.Rd.Tasks.IRdEndpoint`2.Set(System.Func`3<JetBrains.Lifetimes.Lifetime,!0,JetBrains.Rd.Tasks.RdTask`1<!1>>, JetBrains.Collections.Viewable.IScheduler)".

--- EXCEPTION #1/4 [MissingMethodException]
Message = “Метод не найден: "Void JetBrains.Rd.Tasks.IRdEndpoint`2.Set(System.Func`3<JetBrains.Lifetimes.Lifetime,!0,JetBrains.Rd.Tasks.RdTask`1<!1>>, JetBrains.Collections.Viewable.IScheduler)".”
ExceptionPath = Root.InnerException.InnerException.InnerException
ClassName = System.MissingMethodException
HResult = COR_E_MISSINGMETHOD=80131513
Source = AvaloniaRider.Plugin
StackTraceString = “в ReSharperPlugin.AvaloniaRider.RiderProjectOutputHost..ctor(ISolution solution, ILogger logger)”

--- Outer ---

--- EXCEPTION #2/4 [TargetInvocationException]
Message = “Адресат вызова создал исключение.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.Reflection.TargetInvocationException
Data.ThreadLocalDebugInfo = ScheduleNextSolutionLoadTask
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Initializing
InnerException = “Exception #1 at Root.InnerException.InnerException.InnerException”
HResult = COR_E_TARGETINVOCATION=80131604
Source = mscorlib
StackTraceString = “
  в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     в JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     в JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.CreateInstance(IValueResolveContext context)
     в JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     в JetBrains.Application.Components.SingletonDescriptor.GetValue()
     в JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, ICollection`1 dscs, IComponentContainer container)
”

--- Outer ---

--- EXCEPTION #3/4 [TargetInvocationException]
Message = “Component ReSharperPlugin.AvaloniaRider.RiderProjectOutputHost [Singleton, Corrupted] construction has failed.”
ExceptionPath = Root.InnerException
ClassName = System.Reflection.TargetInvocationException
Data.Descriptor = “ReSharperPlugin.AvaloniaRider.RiderProjectOutputHost [Singleton, Corrupted]”
InnerException = “Exception #2 at Root.InnerException.InnerException”
HResult = COR_E_TARGETINVOCATION=80131604

--- Outer ---

--- EXCEPTION #4/4 [LoggerException]
Message = “Component ReSharperPlugin.AvaloniaRider.RiderProjectOutputHost [Singleton, Corrupted] construction has failed.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #3 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  в JetBrains.Diagnostics.LogEx.Error(ILog this, Exception ex, String message) в /opt/buildAgent/work/b0c387553c046bbb/rd-net/Lifetimes/Diagnostics/LogEx.cs:строка 244
     в JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, ICollection`1 dscs, IComponentContainer container)
     в JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
     в JetBrains.ProjectModel.SolutionInstance.OpenSolution(ISolutionOwner solutionOwner, ISolutionLoadTasksScheduler taskScheduler)
     в JetBrains.ProjectModel.SolutionManagerBase.<>c__DisplayClass38_0.<CreateSolutionInstance>b__0()
     в JetBrains.ProjectModel.Tasks.SolutionLoadTasksSchedulerBase.<>c__DisplayClass21_0.<ExecuteTask>b__1()
     в JetBrains.Util.ILoggerEx.Catch(ILogger thіs, Action F, ExceptionOrigin origin, LoggingLevel loggingLevel)
     в JetBrains.ProjectModel.Tasks.SolutionLoadTasksSchedulerBase.ExecuteTask(SolutionLoadTask task)
     в JetBrains.ProjectModel.Tasks.SolutionLoadTasksSchedulerAsync.<Schedule>b__6_0()
     в JetBrains.Application.Threading.IShellLocksEx.ExecuteWithReadLock(IShellLocks thіs, Action F)
     в JetBrains.Threading.ReentrancyGuardEx.<>c__DisplayClass0_1.<Queue>b__3()
     в JetBrains.Threading.ReentrancyGuard.<>c__DisplayClass31_0.<Queue>b__0()
     в JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     в JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     в JetBrains.Threading.JetDispatcher.Closure.Execute()
     в JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     в System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     в System.Windows.Threading.DispatcherOperation.InvokeImpl()
     в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     в System.Windows.Threading.DispatcherOperation.Invoke()
     в System.Windows.Threading.Dispatcher.ProcessQueue()
     в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     в JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     в JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     в JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.InternalPumpMessagesOnce()
     в JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.JetBrains.Util.Concurrency.IJetDispatcherStaticMethods.Run()
     в JetBrains.ReSharper.Host.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)
     в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     в JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()
     в JetBrains.Util.Logging.Logger.Catch(Action action)
     в JetBrains.Threading.JetDispatcher.Closure.Execute()
     в JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     в System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     в System.Windows.Threading.DispatcherOperation.InvokeImpl()
     в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     в System.Windows.Threading.DispatcherOperation.Invoke()
     в System.Windows.Threading.Dispatcher.ProcessQueue()
     в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
     в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
     в JetBrains.Application.Environment.IJetHostEx.<>c__DisplayClass2_0.<RunHostMessageLoop>b__0(Lifetime lifetime)
     в JetBrains.Lifetimes.Lifetime.Using(Action`1 action) в /opt/buildAgent/work/b0c387553c046bbb/rd-net/Lifetimes/Lifetimes/Lifetime.cs:строка 404
     в JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)
     в JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)
     в JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)
     в JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)
     в JetBrains.ReSharper.Host.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)
     в JetBrains.ReSharper.Host.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)
     в JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action) в /opt/buildAgent/work/b0c387553c046bbb/rd-net/Lifetimes/Lifetimes/Lifetime.cs:строка 418
     в JetBrains.ReSharper.Host.Product.RiderBackendProgram.Main()
     в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     в JetBrains.Launcher.Msil.LauncherManagedCore.JetBrains.Launcher.Msil.ILauncherManagedCore.InvokeManagedMethod(String sAssemblyName, String sAssemblyFile, String sClassName, String sMethodName, Int32& phrExitCode, String& bsFailureMessageShort, String& bsFailureMessageLong)
”

	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:49)
	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:24)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:96)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:17)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:22)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ForNeVeR** [comment]
Thanks. It won't be easy to port the plugin to Rider 2021.1, but I'm already working on it.
