### ISSUE TITLE
Reviewer crash after ShowDialog

### ISSUE THREAD

**Issue by SKProCH** [ForNeVeR/AvaloniaRider#131]
When i click button that open open dialog window i get following exception and previewed crash.
You can reproduce it on Material.Avalonia project at DialogDemo page.
```
Socket error while session is still alive

java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:68)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ForNeVeR** [comment]
I wasn't able to reproduce the issue with the latest version. Could you please check if it reproduces? If not, I'd need IDE and previewer process logs to investigate what's wrong.

**Comment by SKProCH** [comment]
@ForNeVeR still can reproduce with latest version from plugins.
![image](https://user-images.githubusercontent.com/29896317/117569956-c03f6b80-b0d0-11eb-8826-a1972769384f.png)
IDE error:
```
Socket error while session is still alive

java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:68)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:245)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Previewer log:
```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig E:\RiderProjects\material.avalonia\Material.Demo\bin\Debug\netcoreapp3.1\Material.Demo.runtimeconfig.json --depsfile E:\RiderProjects\material.avalonia\Material.Demo\bin\Debug\netcoreapp3.1\Material.Demo.deps.json C:\Users\SKProCH\.nuget\packages\avalonia\0.10.0\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:61570/ --method avalonia-remote E:\RiderProjects\material.avalonia\Material.Demo\bin\Debug\netcoreapp3.1\Material.Demo.dll
Obtaining AppBuilder instance from Material.Demo.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'owner')
   at Avalonia.Controls.Window.ShowDialog[TResult](Window owner) in /_/src/Avalonia.Controls/Window.cs:line 706
   at Avalonia.Controls.Window.ShowDialog(Window owner) in /_/src/Avalonia.Controls/Window.cs:line 686
   at Material.Dialog.Bases.DialogWindowBase`2.<>c__DisplayClass5_0.<ShowDialog>b__0() in E:\RiderProjects\material.avalonia\Material.Dialog\Bases\DialogWindowBase.cs:line 24
   at Material.Dialog.Bases.DialogWindowBase`2.Procedure(Action action) in E:\RiderProjects\material.avalonia\Material.Dialog\Bases\DialogWindowBase.cs:line 38
   at Material.Dialog.Bases.DialogWindowBase`2.ShowDialog(Window ownerWindow) in E:\RiderProjects\material.avalonia\Material.Dialog\Bases\DialogWindowBase.cs:line 24
   at Material.Demo.ViewModels.DialogDemoViewModel.Dialog1() in E:\RiderProjects\material.avalonia\Material.Demo\ViewModels\DialogDemoViewModel.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Controls.Platform.InternalPlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Controls/Platform/InternalPlatformThreadingInterface.cs:line 27
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 189
   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 48
Process terminated with exit code -532462766
```

**Comment by ForNeVeR** [comment]
Thanks for taking a look!

Looks like a bug in Material.Avalonia itself which is killing the previewer process (it tries to show a modal dialog inside of a previewer?). I can't do anything about it, sorry.
