### ISSUE TITLE
Exception on Update on version 1.0.0.732985404

### ISSUE THREAD

**Issue by RomanSoloweow** [ForNeVeR/AvaloniaRider#132]
**Versions**
Rider: 2021.1.1
Plugin: 1.0.0.586794664

logs:
![image](https://user-images.githubusercontent.com/29205560/115524976-58e38800-a297-11eb-802e-3daae88bb5f0.png)

java.lang.NoSuchMethodError: 'java.lang.Object com.jetbrains.rider.util.CoroutineUtilKt.startOnUi$default(com.jetbrains.rd.util.lifetime.Lifetime, com.intellij.openapi.application.ModalityState, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation, int, java.lang.Object)'
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController.executePreviewerAsync(AvaloniaPreviewerSessionController.kt:229)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$start$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:292)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by RomanSoloweow** [comment]
After several tries and IDE restarts - update was installed 🤷‍♂️

**Comment by ForNeVeR** [comment]
FYI, there're known issues with plugin updates in Rider 2021.1.1 on Windows.

2021.1.2 is on the way!
