### ISSUE TITLE
java.util.NoSuchElementException: Sequence is empty.

### ISSUE THREAD

**Issue by jinek** [ForNeVeR/AvaloniaRider#156]
Exception happened when creating Window in linux.
![image](https://user-images.githubusercontent.com/10516222/135884656-16063d2c-a38a-480e-9075-e9d4e10b9d68.png)

```
Unhandled coroutine throwable

java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:111)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:51)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:27)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:84)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:144)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt:26)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:56)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:20)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:401)
	at com.jetbrains.rd.util.lifetime.Lifetime.createNested(RLifetime.kt:56)
	at com.jetbrains.rd.util.reactive.SourceExKt.adviseUntil(SourceEx.kt:25)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt.getProjectContainingFile(ProjectModelNodeEx.kt:40)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$fillWithActions$1.invokeSuspend(RunnableAssemblySelectorAction.kt:209)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.jetbrains.rd.framework.util.RdCoroutineScope.launch(RdCoroutineScope.kt:81)
	at com.jetbrains.rd.framework.util.LifetimeCoroutineUtilKt.launch(LifetimeCoroutineUtil.kt:42)
	at com.jetbrains.rd.platform.util.RdCoroutinesUtilKt.launchOnUi(RdCoroutinesUtil.kt:21)
	at com.jetbrains.rd.platform.util.RdCoroutinesUtilKt.launchOnUi$default(RdCoroutinesUtil.kt:19)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.fillWithActions(RunnableAssemblySelectorAction.kt:206)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.access$fillWithActions(RunnableAssemblySelectorAction.kt:47)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:162)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:47)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:185)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:178)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:84)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:144)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1.advise(PropertyCombinators.kt:181)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:117)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2.advise(PropertyCombinators.kt:174)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:162)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:65)
	at me.fornever.avaloniarider.idea.editor.legacy.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:32)
	at me.fornever.avaloniarider.idea.editor.legacy.AvaloniaRemotePreviewEditor.<init>(AvaloniaRemotePreviewEditor.kt:10)
	at me.fornever.avaloniarider.idea.editor.legacy.AvaloniaPreviewEditorProvider.createEditor(AvaloniaPreviewEditorProvider.kt:24)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:997)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:890)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:731)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1269)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1263)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.doOpenTextEditor(FileEditorManagerImpl.java:1336)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openTextEditor(FileEditorManagerImpl.java:1331)
	at com.jetbrains.rdclient.editors.FrontendTextControlHost.openTextEditor(FrontendTextControlHost.kt:338)
	at com.jetbrains.rider.editors.RiderTextControlHost.access$openTextEditor$s2067750782(RiderTextControlHost.kt:41)
	at com.jetbrains.rider.editors.RiderTextControlHost$openTextEditor$1.invoke(RiderTextControlHost.kt:158)
	at com.jetbrains.rider.editors.RiderTextControlHost$openTextEditor$1.invoke(RiderTextControlHost.kt:41)
	at com.jetbrains.rider.projectView.RiderOpenFileDescriptorKt.withProjectModelId(RiderOpenFileDescriptor.kt:71)
	at com.jetbrains.rider.editors.RiderTextControlHost.openTextEditor(RiderTextControlHost.kt:157)
	at com.jetbrains.rdclient.editors.FrontendTextControlHost$ensureEditorOpened$1.run(FrontendTextControlHost.kt:316)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.jetbrains.rdclient.editors.FrontendTextControlHost.ensureEditorOpened(FrontendTextControlHost.kt:306)
	at com.jetbrains.rdclient.editors.FrontendTextControlHost$1$1.invoke(FrontendTextControlHost.kt:107)
	at com.jetbrains.rdclient.editors.FrontendTextControlHost$1$1.invoke(FrontendTextControlHost.kt:59)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:146)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:108)
	at com.jetbrains.rd.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:126)
	at com.jetbrains.rd.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:64)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.ViewableMap.put(ViewableMap.kt:29)
	at com.jetbrains.rd.framework.impl.RdMap.onWireReceived(RdMap.kt:129)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:50)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker.invoke(MessageBroker.kt:49)
	at com.jetbrains.rd.framework.MessageBroker.access$invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.MessageBroker$dispatch$$inlined$lock$lambda$1.invoke(MessageBroker.kt:103)
	at com.jetbrains.rd.framework.MessageBroker$dispatch$$inlined$lock$lambda$1.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:947)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$7(ProgressWindow.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:820)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:225)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
	at com.jetbrains.rider.services.RiderGlobalProgressHostKt.runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:145)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.a(RiderGlobalProgressHost.kt:87)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.access$runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:63)
	at com.jetbrains.rider.services.RiderGlobalProgressHost.runProgress(RiderGlobalProgressHost.kt:60)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runUnderProgress(Extensions.kt:121)
	at com.jetbrains.rider.util.idea.ExtensionsKt$runCommandUnderProgress$1.run(Extensions.kt:160)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runCommandUnderProgress(Extensions.kt:158)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runCommandUnderProgress$default(Extensions.kt:149)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$execute$1.invoke(RiderNewFileFromTemplateActions.kt:132)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$execute$1.invoke(RiderNewFileFromTemplateActions.kt:30)
	at com.jetbrains.rider.document.RiderReloadVetoer$Companion.runWithReloadSuppress(RiderReloadVetoer.kt:25)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase.execute(RiderNewFileFromTemplateActions.kt:131)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1$1.run(RiderNewFileFromTemplateActions.kt:101)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1.consume(RiderNewFileFromTemplateActions.kt:100)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1.consume(RiderNewFileFromTemplateActions.kt:30)
	at com.intellij.ide.ui.newItemPopup.NewItemSimplePopupPanel$1.keyPressed(NewItemSimplePopupPanel.java:108)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6610)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:803)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by craviee** [comment]
Same problem on ArchLinux.
Works fine tho.

**Comment by ForNeVeR** [comment]
This means that the plugin wasn't able to find a project your XAML file belongs to. Could you please attach the IDE logs?

**Comment by KarlKeu00** [comment]
Same problem on MacOS (M1 Pro)
What logs do you need?

**Comment by ForNeVeR** [comment]
Usually, **Help → Collect Logs** provides all the necessary details.

Please inspect the log archive to not accidentally share some private information!

**Comment by manuc66** [comment]
It happened just after cloning and opening this project : https://github.com/mysteryx93/HanumanInstitute.FFmpeg (if it helps to reproduce)

**Comment by ForNeVeR** [comment]
Sadly, I wasn't able to reproduce the issue. Please attach the IDE logs. We have everything logger pretty good (or at least I think so), and it would be easy to figure out what's happening if anybody in this thread would be able to upload them after reproducing the issue.

Without the logs, it is totally unclear what's going on.

**Comment by manuc66** [comment]
@ForNeVeR I've just email you with a link to download the logs on https://mega.nz

**Comment by ForNeVeR** [comment]
Could you please enable logging for `me.fornever.avaloniarider.rider.ProjectModelNodeExKt` (**Help → Diagnostic Tools → Choose Trace Scenarios**: **Advanced log settings** – enter "me.fornever.avaloniarider.rider.ProjectModelNodeExKt"), reproduce the issue again, and send me the logs again?

Only the lines containing substring `ProjectModelNodeExKt` are interesting; there shouldn't be a lot of them in the logs, so should be pretty safe to share publicly.

**Comment by ForNeVeR** [comment]
No answer in more than 2 weeks ⇒ closed, sorry. If you still have the issue or (ideally) can share the project for me to reproduce the issue, please leave a comment. Thanks!

**Comment by maslo2017** [comment]
I faced the same problem. At the same time, everything works in Visual Studio.

Personally, I can’t tell from the logs why, but the plugin cannot find the path to the project. At the same time, the path to `.axaml` was found.

```log
2024-01-16 21:02:36,256 [  14762]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - Controller state change: isBuilding = false, projectFilePath = null
2024-01-16 21:02:36,256 [  14762]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - Suspending preview for file://C:/projects/TotalControl/Launcher/TotalControlLauncher/Views/MainWindow.axaml
2024-01-16 21:02:36,260 [  14766]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - MainWindow.axaml: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Suspended@d7f71c3
2024-01-16 21:02:36,309 [  14815] SEVERE - #c.i.o.r.u.RdCoroutineHost - Unhandled coroutine throwable
java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:112)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:50)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$
2.invoke(ProjectModelNodeEx.kt:39)
```

I have attached an archive with logs.

[rider-logs-20240116-21214712871285684049000320.zip](https://github.com/ForNeVeR/AvaloniaRider/files/13954342/rider-logs-20240116-21214712871285684049000320.zip)

**Comment by ForNeVeR** [comment]
Please open a new issue and attach your solution.
