### ISSUE TITLE
NoSuchElementException  in 1.0.0.1087501416

### ISSUE THREAD

**Issue by RomanSoloweow** [ForNeVeR/AvaloniaRider#166]
Unhandled coroutine throwable

java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:111)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:51)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:27)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:84)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:144)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt:26)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:56)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$$inlined$also$lambda$1.invoke(RLifetime.kt:20)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:401)
	at com.jetbrains.rd.util.lifetime.Lifetime.createNested(RLifetime.kt:56)
	at com.jetbrains.rd.util.reactive.SourceExKt.adviseUntil(SourceEx.kt:25)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt.getProjectContainingFile(ProjectModelNodeEx.kt:40)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$fillWithActions$1.invokeSuspend(RunnableAssemblySelectorAction.kt:209)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.jetbrains.rd.framework.util.RdCoroutineScope.launch(RdCoroutineScope.kt:81)
	at com.jetbrains.rd.framework.util.LifetimeCoroutineUtilKt.launch(LifetimeCoroutineUtil.kt:42)
	at com.jetbrains.rd.platform.util.RdCoroutinesUtilKt.launchOnUi(RdCoroutinesUtil.kt:21)
	at com.jetbrains.rd.platform.util.RdCoroutinesUtilKt.launchOnUi$default(RdCoroutinesUtil.kt:19)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.fillWithActions(RunnableAssemblySelectorAction.kt:206)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.access$fillWithActions(RunnableAssemblySelectorAction.kt:47)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:162)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:47)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:185)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:178)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:27)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:84)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:144)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1.advise(PropertyCombinators.kt:181)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:117)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2.advise(PropertyCombinators.kt:174)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:162)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:65)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:52)
	at me.fornever.avaloniarider.idea.editor.AvaloniaRemotePreviewEditor.<init>(AvaloniaRemotePreviewEditor.kt:9)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewerXamlEditorExtension.createEditor(AvaloniaPreviewerXamlEditorExtension.kt:22)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:125)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:41)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:21)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:15)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:20)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty$WriteOnceSignal.fire(Property.kt:120)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty.setIfEmpty(Property.kt:84)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:96)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:135)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:945)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$7(ProgressWindow.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:820)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:225)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
	at com.jetbrains.rider.services.RiderGlobalProgressHostKt.runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:145)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.a(RiderGlobalProgressHost.kt:87)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.access$runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:63)
	at com.jetbrains.rider.services.RiderGlobalProgressHost.runProgress(RiderGlobalProgressHost.kt:60)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runUnderProgress(Extensions.kt:121)
	at com.jetbrains.rider.util.idea.ExtensionsKt$runCommandUnderProgress$1.run(Extensions.kt:160)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runCommandUnderProgress(Extensions.kt:158)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runCommandUnderProgress$default(Extensions.kt:149)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$execute$1.invoke(RiderNewFileFromTemplateActions.kt:132)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$execute$1.invoke(RiderNewFileFromTemplateActions.kt:30)
	at com.jetbrains.rider.document.RiderReloadVetoer$Companion.runWithReloadSuppress(RiderReloadVetoer.kt:25)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase.execute(RiderNewFileFromTemplateActions.kt:131)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1$1.run(RiderNewFileFromTemplateActions.kt:101)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1.consume(RiderNewFileFromTemplateActions.kt:100)
	at com.jetbrains.rider.projectView.actions.newFile.RiderNewFileFromTemplateActionBase$actionPerformed$1.consume(RiderNewFileFromTemplateActions.kt:30)
	at com.intellij.ide.ui.newItemPopup.NewItemSimplePopupPanel$1.keyPressed(NewItemSimplePopupPanel.java:108)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6610)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:801)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ForNeVeR** [comment]
This means we found an XAML file which doesn't belong to any of the projects in the solution.

Does it reproduce often? Do you have stable steps to reproduce this problem?

**Comment by tpetruk** [comment]
I have just faced this error when creating an Avalonia user control for the first time. Subsequent creations didn't cause an error.

**Comment by ForNeVeR** [comment]
Aha, that's interesting. Probably we'll have to wait a bit in case we couldn't find the file in the project model immediately after it being created. I'll take a look.
