### ISSUE TITLE
Faults when opened

### ISSUE THREAD

**Issue by mike-ward** [ForNeVeR/AvaloniaRider#172]
Installed and tried to preview an Avalonia UserControl. Event log shows fault below.

Rider: 2021.3.1, Windows 10.

Project: https://github.com/mike-ward/Loon

Let me know what I can do to help diagnose the issue.

```
Socket error while session is still alive

java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:66)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:274)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ForNeVeR** [comment]
Please take a look at the Avalonia Previewer logs, they may contain useful information.

**Comment by mike-ward** [comment]
The Avalonia Designer window has the following message:

```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\mike\Documents\GitHub\Loon\src\Loon\bin\Debug\net6.0\Loon.runtimeconfig.json --depsfile C:\Users\mike\Documents\GitHub\Loon\src\Loon\bin\Debug\net6.0\Loon.deps.json C:\Users\mike\.nuget\packages\avalonia\0.10.10\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:52187/ --method avalonia-remote C:\Users\mike\Documents\GitHub\Loon\src\Loon\bin\Debug\net6.0\Loon.dll
Loon.Program doesn't have a method named BuildAvaloniaApp
Process terminated with exit code 1
```

**Comment by ForNeVeR** [comment]
Okay, so, it looks like your `Loon.Program` doesn't have a method named `BuildAvaloniaApp`. Not a plugin issue, but a problem with your program not being compatible with the previewer.

Please take a look at the template project and how `BuildAvaloniaApp` is defined there. The previewer expects a method with this signature in your program and uses that.

**Comment by mike-ward** [comment]
Made the recommended changes (pushed to  main branch). The previewer window displays this fault:

```
XamlTypeSystemException: Unable to resolve type Loon.Views.TitleBar XamlX.XamlTypeSystemException: Unable to resolve type Loon.Views.TitleBar 
at XamlX.TypeSystem.XamlTypeSystemExtensions.GetType(IXamlTypeSystem sys, String type) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/TypeSystem/TypeSystem.cs:line 303 
at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlTypeBuilder`1 tb, IXamlType overrideRootType) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs:line 122 
at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 196 
at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 158 
at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 258 
at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) in /_/src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs:line 13 
at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) in /_/src/Avalonia.DesignerSupport/DesignWindowLoader.cs:line 33 
at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0() in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 233
```

**Comment by mike-ward** [comment]
Figured it out. The views have to be `public`. Kind of makes sense given the plugin as to see them. I usually use `internal` because Rider indicates it can be `internal`
