### ISSUE TITLE
Preview is blank when styles are not properly imported: "Socket error while session is still alive"

### ISSUE THREAD

**Issue by Namek** [ForNeVeR/AvaloniaRider#176]
So this happened to me yesterday. Blank screen in the preview window, no error, no feedback.

IDE version: JetBrains Rider 2021.3.2

![image](https://user-images.githubusercontent.com/31058/147825984-74dda3ee-8a12-4274-acbb-2010e1ce0c29.png)

```
Socket error while session is still alive

java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:66)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:274)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It turned out that the issue was bad Source URI for `StyleInclude`  in `Application.Styles`:
![image](https://user-images.githubusercontent.com/31058/147826494-5bfd18f8-6f57-4393-a0f7-7027d25640e7.png)
(the 2nd one) which was a result of autocompletion.

**Comment by ForNeVeR** [comment]
> Blank screen in the preview window, no error, no feedback.

Could you please check the **Avalonia** tool window? Logs should be there.

I understand that it's not very discoverable in its current state, and there're plans to improve this. But there should be logs, and probably the previewer process has actually crashed.

**Comment by ForNeVeR** [comment]
Without your feedback, the issue is non-actionable. Closed.
