### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property writer has not been initialized

### ISSUE THREAD

**Issue by Namek** [ForNeVeR/AvaloniaRider#177]
This happens pretty often so I get this bad dude on my screen's bottom right corner:

![image](https://user-images.githubusercontent.com/31058/147826555-0063eb2f-ecbc-448f-9f08-4c134f7bdf92.png)

```
Catch

kotlin.UninitializedPropertyAccessException: lateinit property writer has not been initialized
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.sendInputEventMessage(AvaloniaPreviewerSession.kt:98)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController.sendInputEventMessage(AvaloniaPreviewerSessionController.kt:335)
	at me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent$frameBufferView$1$1$1.invoke(BitmapPreviewEditorComponent.kt:37)
	at me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent$frameBufferView$1$1$1.invoke(BitmapPreviewEditorComponent.kt:36)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at me.fornever.avaloniarider.previewer.AvaloniaMessageMouseListener.sendPointerMovedEventMessage(AvaloniaMessageMouseListener.kt:69)
	at me.fornever.avaloniarider.previewer.AvaloniaMessageMouseListener.mouseMoved(AvaloniaMessageMouseListener.kt:58)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6699)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3363)
	at java.desktop/java.awt.Component.processEvent(Component.java:6423)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ForNeVeR** [comment]
Hm, this is interesting. Probably we have a race condition here, I'll check. Thanks!
