### ISSUE TITLE
EOFException at startup

### ISSUE THREAD

**Issue by louhy** [ForNeVeR/AvaloniaRider#222]
With this repo: https://github.com/Jacudibu/PRUNner 

Here's what Rider reports: 

Socket error while session is still alive

java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:64)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:299)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

This is from a Linux Mint PC.

**Comment by louhy** [comment]
If you mean this "Avalonia Designer" tab (didn't notice it until I went looking for this log), we do have a bit more: 

```
/usr/share/dotnet/dotnet exec --runtimeconfig /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.runtimeconfig.json --depsfile /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.deps.json /home/louhy/.nuget/packages/avalonia/0.10.18/buildTransitive/../tools/netcoreapp2.0/designer/Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:37475/ --method avalonia-remote /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.dll
Obtaining AppBuilder instance from PRUNner.Program.BuildAvaloniaApp
Initializing application in design mode
Unhandled exception. System.Exception: Unsupported Environment!
   at PRUNner.App.App.OnFrameworkInitializationCompleted() in /home/louhy/git/PRUNner/PRUNner/App/App.axaml.cs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithoutStarting() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 167
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 154
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 179
   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47
Process terminated with exit code 134
```

**Comment by ForNeVeR** [comment]
Well, it means that something in your app throws an "Unsupported Environment" exception when started from the previewer.

**Comment by louhy** [comment]
If you think it's from the application itself, I'll have to dig deeper. It's not my application, I've just cloned it from GitHub, so I can't really answer the question yet.

**Comment by louhy** [comment]
As far as I can tell, it seems like it doesn't like accessing a file for style configuration like this: 

```
    <Application.Styles>
        <FluentTheme Mode="Dark"/>
        
        <StyleInclude Source="/App/Styles/NumericUpDownCompact.axaml"/>
        ...
```

When I remove that, clean, and restart, the error goes away. Keeping in mind I'm on Linux (it seems like a filesystem access problem, maybe), if you have any ideas for a solution or workaround I'd be interested.

**Comment by ForNeVeR** [comment]
It could be, but I really have no idea. The stack trace is either from the application you're opening or the Avalonia previewer, and not the AvaloniaRider code. So, you better report this to Avalonia folks, I think.

**Comment by louhy** [comment]
Hmm, well thanks for taking a look in any case.

**Comment by louhy** [comment]
What's weird though is if I remove that line 31 that second exception points to, both errors go away, and the Avalonia Designer tab only shows this (no idea how crucial that deps.json error is): 


```
/usr/share/dotnet/dotnet exec --runtimeconfig /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.runtimeconfig.json --depsfile /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.deps.json /home/louhy/.nuget/packages/avalonia/0.10.18/buildTransitive/../tools/netcoreapp2.0/designer/Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:34207/ --method avalonia-remote /home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.dll
The specified deps.json [/home/louhy/git/PRUNner/PRUNner/bin/Debug/net6.0/PRUNner.deps.json] does not exist
Process terminated with exit code 129

```

Previews still don't render either, which is not surprising given the last line. I think I'll try setting up my own "empty" project to see if that works, maybe it's not even related to this particular repo.

**Comment by ForNeVeR** [comment]
`deps.json` is required. It is very strange that it is absent. Have you built the project?

**Comment by louhy** [comment]
Comment out line 31, Build->Clean Solution, restart. Then I get that deps.json error. 
Okay, maybe I need to manually build and run... 

.. at the moment that's getting back to the "Unsupported Environment!" stack trace in the designer tab, even though line 31 in App.axaml.cs is completely different now. Hmm.. yeah that's confusing. 

The application RUNS fine, I even had it hit a debug breakpoint before. Think I'll need to try that new project test approach to see if I can reproduce it.

**Comment by ForNeVeR** [comment]
I was able to easily make it run. Comment line 31, rebuild → the preview works.

It is, indeed, broken by default (probably because the previewer gives the application some other lifetime, not an `IClassicDesktopStyleApplicationLifetime`).

Not something we control from the plugin, though.

**Comment by louhy** [comment]
Well that's wierd becuase I've been doing exactly that and could never get anything to work. Maybe it's Linux specific.
