### ISSUE TITLE
Ошибка работы плагина

### ISSUE THREAD

**Issue by anst-foto** [ForNeVeR/AvaloniaRider#235]
При запуске программы из Rider выскакивает сообщение об ошибке

Socket error while session is still alive

```
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:64)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invokeSuspend(AvaloniaPreviewerSessionController.kt:299)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Версия Rider
```
JetBrains Rider 2022.2.3
Build #RD-222.4167.23, built on September 9, 2022
For educational use only.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.21.0)
    me.seclerp.rider.plugins.efcore (222.2.0)
    idea.plugin.protoeditor (222.4167.21)
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.12)
    com.pvsstudio.dotnet (7.21.64848)
    com.intellij.resharper.StructuredLogging (2022.2.3.266)
    com.intellij.resharper.HeapAllocationsViewer (2022.2.0)
    com.intellij.javafx (1.0.4)
    com.intellij.ideolog (203.0.30.0)
    avalonia-rider (1.0.0.2140933520)
    com.jetbrains.rider.android (222.4167.23)
    PlantUML integration (5.19)
    org.sonarlint.idea (7.1.1.54565)
    mobi.hsz.idea.gitignore (4.4.2)
    cn.yiiguxing.plugin.translate (3.3.5)
    Abc.MoqComplete.Rider (2022.2.0.2)
```

**Comment by ForNeVeR** [comment]
Duplicate of #84.
