### ISSUE TITLE
Critical Error Rider 2022.3.1

### ISSUE THREAD

**Issue by Cinorid** [ForNeVeR/AvaloniaRider#254]
Jetbrains Rider 2022.3.1 error log:

```
com.intellij.diagnostic.PluginException: me.fornever.avaloniarider.statistics.PreviewerUsageLogger PluginClassLoader(plugin=PluginDescriptor(name=AvaloniaRider, id=avalonia-rider, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2022.3\plugins\avaloniarider, version=1.0.1.99, package=null, isBundled=false), packagePrefix=null, instanceId=34, state=active)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1014)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.lambda$instantiateCounterCollectors$1(FUCounterUsageLogger.java:86)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:153)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.instantiateCounterCollectors(FUCounterUsageLogger.java:84)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.logRegisteredGroups(FUCounterUsageLogger.java:102)
	at com.intellij.internal.statistic.service.fus.collectors.FUCounterUsageLogger.lambda$new$0(FUCounterUsageLogger.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: me.fornever.avaloniarider.statistics.PreviewerUsageLogger PluginClassLoader(plugin=PluginDescriptor(name=AvaloniaRider, id=avalonia-rider, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2022.3\plugins\avaloniarider, version=1.0.1.99, package=null, isBundled=false), packagePrefix=null, instanceId=34, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1519)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1006)
	... 16 more
```

**Comment by ForNeVeR** [comment]
The component in question was, indeed, removed from the plugin (we need no statistics), but it looks like I forgot to remove the corresponding registration from the `plugin.xml`. Thanks for report, I'll fix this ASAP.
