### ISSUE TITLE
Designer not showing Datagrid

### ISSUE THREAD

**Issue by Sophisticated-IS** [ForNeVeR/AvaloniaRider#259]
Is DataGrid Supported?
DataGrid is not showing at all.
Also, If I add DataGrid to controls tree the Designer freezes and does not update any more. 

Avalonia Version: 1.0.3.103
Rider:2022.3.1
OS: Window 10

**Comment by ForNeVeR** [comment]
Please check the previewer logs (obtainable via a toolbar button). Do they contain anything interesting?

**Comment by Sophisticated-IS** [comment]
```
Process terminated with exit code 1"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.runtimeconfig.json" --depsfile "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.deps.json" "C:\Users\Igor SI\.nuget\packages\avalonia\0.10.18\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll" --transport tcp-bson://127.0.0.1:62123/ --method avalonia-remote "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.dll"
Obtaining AppBuilder instance from AvaloniaAppBugDesigner.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
Process terminated with exit code 1"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.runtimeconfig.json" --depsfile "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.deps.json" "C:\Users\Igor SI\.nuget\packages\avalonia\0.10.18\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll" --transport tcp-bson://127.0.0.1:62128/ --method avalonia-remote "C:\Users\Igor SI\RiderProjects\AvaloniaAppBugDesigner\AvaloniaAppBugDesigner\bin\Release\net6.0\AvaloniaAppBugDesigner.dll"
Obtaining AppBuilder instance from AvaloniaAppBugDesigner.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
```

**Comment by Sophisticated-IS** [comment]
repro
[AvaloniaAppBugDesigner.zip](https://github.com/ForNeVeR/AvaloniaRider/files/10398505/AvaloniaAppBugDesigner.zip)

**Comment by Sophisticated-IS** [comment]
I am not sure but may it is avalonia bug not designer because I do not see datagrid after executing App even if I set width and Height to fixed values and set background color. At start It is not showing at all. Just empty window.

**Comment by Sophisticated-IS** [comment]
Also If i put an empty DataGrid into normally showing window axaml it freezes. 
![image](https://user-images.githubusercontent.com/57034720/211986960-a06d03df-a9b1-4bc1-957c-74a698f68ed3.png)

*Logs are the same as above

**Comment by JenyaRostov** [comment]
Might want to check idea.log

**Comment by Sophisticated-IS** [comment]
Oh, my bad) I found it)

```
2023-01-12 18:02:37,595 [  37859]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - App.axaml: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@1ad5b10a
2023-01-12 18:02:37,597 [  37861]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - MainWindow.axaml: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@1ad5b10a
2023-01-12 18:02:37,622 [  37886]   INFO - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - Status: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@1ad5b10a
2023-01-12 18:02:37,623 [  37887]   INFO - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - Status: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@1ad5b10a
2023-01-12 18:02:38,264 [  38528]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Error from UpdateXamlResultMessage: XamlX.XamlParseException: Unable to resolve type DataGrid from namespace https://github.com/avaloniaui Line 15, position 10.
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 109
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 35
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 147
   at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 135
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/AstTransformationContext.cs:line 58
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 56
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 76
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 74
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 78
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 74
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 78
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Compiler/XamlCompiler.cs:line 67
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlTypeBuilder`1 tb, IXamlType overrideRootType) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs:line 141
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 196
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 158
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 258
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) in /_/src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs:line 13
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) in /_/src/Avalonia.DesignerSupport/DesignWindowLoader.cs:line 33
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0() in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 233
2023-01-12 18:02:38,322 [  38586]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - MainWindow.axaml: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$XamlError@3abcf0a9
2023-01-12 18:02:38,379 [  38643]   INFO - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - Status: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$XamlError@3abcf0a9
2023-01-12 18:02:38,380 [  38644]   WARN - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - XAML update error: XamlParseException at 15:10: Unable to resolve type DataGrid from namespace https://github.com/avaloniaui Line 15, position 10.
XamlX.XamlParseException: Unable to resolve type DataGrid from namespace https://github.com/avaloniaui Line 15, position 10.
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 109
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 35
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 147
   at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/Transformers/TypeReferenceResolver.cs:line 135
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/AstTransformationContext.cs:line 58
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 56
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 76
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 74
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 78
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 74
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Xaml.cs:line 78
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Ast/Common.cs:line 60
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Compiler/XamlCompiler.cs:line 67
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlTypeBuilder`1 tb, IXamlType overrideRootType) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs:line 141
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 196
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 158
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 258
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) in /_/src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs:line 13
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) in /_/src/Avalonia.DesignerSupport/DesignWindowLoader.cs:line 33
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0() in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 233
```

**Comment by Sophisticated-IS** [comment]
I solved the problem by adding style to app.xaml. I didn't think that style is obligatory)
![image](https://user-images.githubusercontent.com/57034720/212077618-8e0812cb-c7ca-4331-ab8c-58556a579a83.png)

**Comment by ForNeVeR** [comment]
Alright, so this wasn't a previewer problem.

Still, I agree that we could do much better by exposing the error to the user. I've opened an issue #260 about that.
