### ISSUE TITLE
Previewer throws exception

### ISSUE THREAD

**Issue by WizMe-M** [ForNeVeR/AvaloniaRider#270]
When I run previewer, It logs that exception was thrown. It not affects anything, but annoys

### Plugin version
AvaloniaRider 1.0.3.104

### Logs

```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.runtimeconfig.json --depsfile C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.deps.json C:\Users\timki\.nuget\packages\avalonia\0.10.18\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:51853/ --method avalonia-remote C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.dll
Obtaining AppBuilder instance from AvaloniaApplication2.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 62
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 87
Process terminated with exit code 1"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.runtimeconfig.json --depsfile C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.deps.json C:\Users\timki\.nuget\packages\avalonia\0.10.18\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:51862/ --method avalonia-remote C:\Users\timki\RiderProjects\AvaloniaApplication2\AvaloniaApplication2\bin\Debug\net7.0\AvaloniaApplication2.dll
Obtaining AppBuilder instance from AvaloniaApplication2.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
```

### Steps to reproduce:
1. Create **MVVM app** from Avalonia templates  for **.net7**
2. Open previewer for View (e.g. MainWindow)
3. Run previewer

**Comment by ForNeVeR** [comment]
Normally, this means the connection was terminated by the frontend side of the previewer.

How does that annoy you? The console should be hidden by default, I think.

**Comment by ForNeVeR** [comment]
Sorry, still doesn't answer the question. How does it annoy you? How do you even know there's an issue? The console is hidden by default. Do you open it? Why?

**Comment by ForNeVeR** [comment]
Ok, now I understand. I'll see if it's possible to shut down the Avalonia previewer cleanly without it logging errors on termination.
