### ISSUE TITLE
Not compatible with Rider 2023.2 EAP 6

### ISSUE THREAD

**Issue by MrJul** [ForNeVeR/AvaloniaRider#283]
`WorkspaceModel` seems to have been removed in EAP 6, causing the previewer to crash.
Opening this issue to let you know, I'm not expecting a new release for every EAP version, they're EAP after all :)

```
java.lang.NoClassDefFoundError: com/intellij/workspaceModel/ide/WorkspaceModel
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:70)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:117)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:53)
	at me.fornever.avaloniarider.idea.editor.AvaloniaRemotePreviewEditor.<init>(AvaloniaRemotePreviewEditor.kt:11)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewerXamlEditorExtension.createEditor(AvaloniaPreviewerXamlEditorExtension.kt:22)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:166)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:163)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:19)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:18)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:24)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:23)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty$WriteOnceSignal.fire(Property.kt:122)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty.setIfEmpty(Property.kt:86)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask$onWireReceived$4.invoke(RdTask.kt:134)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask$onWireReceived$4.invoke(RdTask.kt:133)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:122)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:115)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:103)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:29)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.workspaceModel.ide.WorkspaceModel PluginClassLoader(plugin=PluginDescriptor(name=AvaloniaRider, id=avalonia-rider, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2023.2\plugins\avaloniarider, version=1.0.4, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 57 more
```

**Comment by ForNeVeR** [comment]
Oh gosh, thanks for the report, I'll take a look ASAP.
