### ISSUE TITLE
NoSuchMethodError on 2023.3 EAP 1

### ISSUE THREAD

**Issue by sfwtn** [ForNeVeR/AvaloniaRider#297]
Hi, I downloaded Rider 2023.3 EAP 1 and AvaloniaRider 1.1.0.114 and after creating a template Avalonia App and loading in, it threw this error:
```
java.lang.NoSuchMethodError: 'kotlinx.coroutines.Job com.intellij.openapi.rd.util.RdCoroutinesUtilKt.launchOnUi$default(com.jetbrains.rd.util.lifetime.Lifetime, kotlinx.coroutines.CoroutineStart, kotlin.jvm.functions.Function2, int, java.lang.Object)'
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.fillWithActions(RunnableAssemblySelectorAction.kt:207)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.access$fillWithActions(RunnableAssemblySelectorAction.kt:48)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:163)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$1.invoke(RunnableAssemblySelectorAction.kt:163)
	at com.jetbrains.rd.util.reactive.IPropertyBase$view$1$1.invoke(Interfaces.kt:78)
	at com.jetbrains.rd.util.reactive.IPropertyBase$view$1$1.invoke(Interfaces.kt:77)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:185)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1$advise$1.invoke(PropertyCombinators.kt:181)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt:194)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:28)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:129)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:209)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2$change$1.advise(PropertyCombinators.kt:181)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:117)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2.advise(PropertyCombinators.kt:174)
	at com.jetbrains.rd.util.reactive.IPropertyBase$DefaultImpls.view(Interfaces.kt:77)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.view(Interfaces.kt:107)
	at com.jetbrains.rd.util.reactive.PropertyCombinatorsKt$map$2.view(PropertyCombinators.kt:174)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:163)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.<init>(RunnableAssemblySelectorAction.kt:66)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:117)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.<init>(AvaloniaPreviewEditorBase.kt:53)
	at me.fornever.avaloniarider.idea.editor.AvaloniaRemotePreviewEditor.<init>(AvaloniaRemotePreviewEditor.kt:11)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewerXamlEditorExtension.createEditor(AvaloniaPreviewerXamlEditorExtension.kt:22)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:166)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:163)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:19)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:18)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:24)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:23)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty$WriteOnceSignal.fire(Property.kt:122)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty.setIfEmpty(Property.kt:86)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask$onWireReceived$4.invoke(RdTask.kt:134)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask$onWireReceived$4.invoke(RdTask.kt:133)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:122)
	at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:115)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:109)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:33)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:844)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:464)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1431)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:677)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:579)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:579)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:70)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:350)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:344)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:989)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:989)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:344)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:849)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:386)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
``` 
Really not sure what to make of it considering this is just a default template. Something broke in the new version?
Additional Rider info:
```
Build version: JetBrains Rider 2023.3 EAP 1 Build: #RD-233.6745.316 September 24, 2023
JRE: 17.0.8.1+7-b1059.3, JetBrains s.r.o.
JVM: 17.0.8.1+7-b1059.3, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.1.55-1-lts (amd64)
BuildTool: DotNetCoreMsBuild 17.0 (/usr/share/dotnet/sdk/7.0.111/MSBuild.dll)
MonoRuntime: <NONE>
.NET Core SDK CLI: /usr/share/dotnet/dotnet
.NET Core SDK: 7.0.111(7.0.111)
.NET Core Runtimes: 
* JetBrains.Application.platforms.DotNetCoreRuntimeGroup
```

**Comment by ForNeVeR** [comment]
Something must've been changed in Rider internal API. Thanks for report, I'm looking into it.
