### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by ddorab** [ForNeVeR/AvaloniaRider#304]
I know there's a couple other issues open about this but they don't seem to mention the same things.

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/45337750/4f1f6e3c-25c7-4c3a-90ae-23dcc0adf9e3)

```
Obtaining AppBuilder instance from Lumper.UI.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
Process terminated with exit code 1"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\boyac\Documents\dev\lumper\src\Lumper.UI\bin\Debug\net7.0\Lumper.UI.runtimeconfig.json --depsfile C:\Users\boyac\Documents\dev\lumper\src\Lumper.UI\bin\Debug\net7.0\Lumper.UI.deps.json C:\Users\boyac\.nuget\packages\avalonia\11.0.0-preview4\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:62632/ --method avalonia-remote C:\Users\boyac\Documents\dev\lumper\src\Lumper.UI\bin\Debug\net7.0\Lumper.UI.dll
```
[Here](https://github.com/ddorab/lumper)'s the link to the repo.

.NET Version: 7.0.402

**Comment by ForNeVeR** [comment]
Reproduced in VS, moved to upstream: https://github.com/AvaloniaUI/Avalonia/issues/13399
