### ISSUE TITLE
When open the design windows, will report the error.

### ISSUE THREAD

**Issue by jsparrow58** [ForNeVeR/AvaloniaRider#320]
follow is the error description:

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/10719899/b8cd654d-bb2b-4c44-bc67-d7f9f1bd1b3c)

Unhandled coroutine throwable

java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:112)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:50)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:39)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:35)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:34)
	at com.jetbrains.rd.util.reactive.IOptPropertyView$DefaultImpls.advise(Interfaces.kt:118)
	at com.jetbrains.rd.util.reactive.IOptProperty$DefaultImpls.advise(Interfaces.kt:194)
	at com.jetbrains.rd.util.reactive.OptProperty.advise(Property.kt:28)
	at com.jetbrains.rd.framework.impl.RdPropertyBase.advise(RdProperty.kt:129)
	at com.jetbrains.rd.framework.impl.RdOptionalProperty.advise(RdProperty.kt:209)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt:34)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1.invoke(SourceEx.kt:33)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$1$1.invoke(RLifetime.kt:147)
	at com.jetbrains.rd.util.lifetime.Lifetime$createNested$1$1.invoke(RLifetime.kt:147)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:294)
	at com.jetbrains.rd.util.lifetime.Lifetime.createNested(RLifetime.kt:147)
	at com.jetbrains.rd.util.reactive.SourceExKt.adviseUntil(SourceEx.kt:33)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt.getProjectContainingFile(ProjectModelNodeEx.kt:39)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.getSelectableRunnableProjects(RunnableAssemblySelectorAction.kt:236)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction.access$getSelectableRunnableProjects(RunnableAssemblySelectorAction.kt:50)
	at me.fornever.avaloniarider.idea.editor.actions.RunnableAssemblySelectorAction$fillWithActions$1.invokeSuspend(RunnableAssemblySelectorAction.kt:224)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by ForNeVeR** [comment]
Please attach a project for me to reproduce, and/or add more details.

**Comment by jsparrow58** [comment]
[AvaloniaApplication1.zip](https://github.com/ForNeVeR/AvaloniaRider/files/14045098/AvaloniaApplication1.zip)
attachment is the project.
