### ISSUE TITLE
Previewer Fails to Preview

### ISSUE THREAD

**Issue by IsaacMarovitz** [ForNeVeR/AvaloniaRider#324]
<img width="1552" alt="Screenshot 2024-02-08 at 20 43 48" src="https://github.com/ForNeVeR/AvaloniaRider/assets/42140194/9bbb7377-f102-448b-a9a0-a6f37674a4fa">

Preview is blank and throws no error. Problem persists on every attempted `.axaml`

Avalonia Version: 11.0.7
Rider Version: 2023.3.3
AvaloniaRider Version: 1.3.0
OS: macOS Sonoma 14.4
Project: [Ryujinx](https://github.com/Ryujinx/Ryujinx)

The namespace for all Avalonia-related files is `Ryujinx.Ava`. The example shown in the screenshot is `AboutWindow.axaml` in `Ryujinx.Ava/UI/Windows/AboutWindow.axaml` but this same issue occurs in all other files.

**Comment by IsaacMarovitz** [comment]
Persists in version 1.3.1 with Rider 2024.1 EAP 3

**Comment by ForNeVeR** [comment]
Could you please check the IDE logs? Are there any error messages from the previewer?

**Comment by IsaacMarovitz** [comment]
There's a `NullReferenceException` getting thrown:

```
2024-02-09 09:13:54,283 [44320680]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - 1/4: generating process command line
2024-02-09 09:13:54,283 [44320680]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - Starting socket listener
2024-02-09 09:13:54,283 [44320680]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - 2/3: starting a process
2024-02-09 09:13:54,286 [44320683]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - Starting process /usr/local/share/dotnet/dotnet exec --runtimeconfig /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.runtimeconfig.json --depsfile /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.deps.json /Users/isaacmarovitz/.nuget/packages/avalonia/11.0.9/buildTransitive/../tools/netcoreapp2.0/designer/Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:49250/ --method avalonia-remote /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.dll
2024-02-09 09:13:54,286 [44320683]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - AboutWindow.axaml (port 49250) [system]: /usr/local/share/dotnet/dotnet exec --runtimeconfig /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.runtimeconfig.json --depsfile /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.deps.json /Users/isaacmarovitz/.nuget/packages/avalonia/11.0.9/buildTransitive/../tools/netcoreapp2.0/designer/Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:49250/ --method avalonia-remote /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/bin/Debug/net8.0/Ryujinx.Ava.dll

2024-02-09 09:13:54,286 [44320683]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - 3/3: awaiting termination
2024-02-09 09:13:54,344 [44320741]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - AboutWindow.axaml (port 49250) [stdout]: Initializing application in design mode

2024-02-09 09:13:54,347 [44320744]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - AboutWindow.axaml (port 49250) [stdout]: Obtaining AppBuilder instance from Ryujinx.Ava.Program

2024-02-09 09:13:54,621 [44321018]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerProcess - AboutWindow.axaml (port 49250) [stdout]: Sending StartDesignerSessionMessage

2024-02-09 09:13:54,634 [44321031]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController - AboutWindow.axaml: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@6d47e03
2024-02-09 09:13:54,634 [44321031]   INFO - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - Status: me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$Status$Working@6d47e03
2024-02-09 09:13:55,394 [44321791]   INFO - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Error from UpdateXamlResultMessage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ava.UI.ViewModels.AboutWindowViewModel..ctor() in /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/AboutWindowViewModel.cs:line 90
   at Ryujinx.Ava.UI.Windows.AboutWindow..ctor() in /Users/isaacmarovitz/Documents/Ryujinx/src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml.cs:line 20
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadOrPopulate(Type created, Object rootInstance, IServiceProvider parentServiceProvider)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.<>c.<LoadGroupSreCore>b__16_2(ValueTuple`2 t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
```

**Comment by IsaacMarovitz** [comment]
Okay, I've figured out that the problem with Ryujinx is the use of Singleton helpers at runtime. We use both a `ConfigurationState` and `LocaleManager`, I'm unsure how to make these Preview-friendly.

**Comment by IsaacMarovitz** [comment]
Fixed

**Comment by ForNeVeR** [comment]
For the record, the problem of the previewer not showing the XAML exceptions is currently tracked as #316.
